In [1]:
#!/usr/bin/env python3 

In [2]:
# Author: 
# Description: 
# Date Created: 
# Date Modified: 

<p>
<ol> 

<li> Transformation, affine and non affine </li>  
<li> Translations </li>    
<li> Rotations </li> 
<li> Scaling, re-sizing and interpolations </li> 
<li> Image Pyramids </li> 
<li> Cropping </li> 
<li> Arithmetic Operations </li> 
<li> Bitwise Operations and Masking </li> 
<li> Convolutions & Blurring </li> 
<li> Sharpening </li> 
<li> Thresholding and Binarization </li> 
<li> Dilation, erosion, opening and closing </li> 
<li> Edge Detection & Image Gradients </li> 
<li> Perspective & Affine Transforms </li> 
       
</ol> 
</p> 

<h3> Transformations </h3> 
<p> <b> Transformation </b> - are geometric distortions enacted upon an image. <br> 
We use transformations to correct distortions or perspective issues from arising from the point of view an image was captured. </p> 

<p> 
<b> Types: </b> 
<ul> 
<li> Affine: <p> Affine transformations include <b>Scaling</b>, <b>Rotation</b> and <b> Translation </b> 

</li>  <br> 
<li> Non-Affine: <p> Non-Affine or <b>Projective Transform</b> and also called <b>Homography.</b> It does not preserve parallelism, length, and angle. It does however preserve collinearity and incidence. <br> 
Non-Affine transformations are very common in computer vision. 
</p>  
    
    
</li> 
</ul> 
</p> 


<h3> Translation </h3> 
<p> <b>Tx</b> represents the shift along the x-axis (horizontal) <br> 
    <b>Ty</b> represents the shift along the y-axis (vertical) <br> 
    
</p> 

In [3]:
# Importing the necessary modules 
import os 
import cv2 
import numpy as np 

In [15]:
# Setting the path to the image 
IMG_PATH = "images/grande2.jpg" 

# Reading the image into memory 
image = cv2.imread(IMG_PATH) 

# Resizing the image  
image = cv2.resize(image, (600, 600))

# Store the height and width of the image 
height, width = image.shape[:2]

# Finding the quater_height, and quater_width of the image  
quarter_height, quarter_width = height/4, width/4 

# Finding half_height and half_width of the image  
half_height, half_width = height/2, width/2 

# Creating the translation matrix 
T = np.float32([[1, 0, quarter_width], [0, 1, quarter_height]])

# Creating the translation matrix of half values 
T_half = np.float32([[1, 0, half_width], [0, 1, half_height]])

# Transforming the image by using the warpAffine function and the matrix T 
img_translation = cv2.warpAffine(image, T, (width, height))

# Transforming the image by using the warpAffine function for half_ 
img_half_translation = cv2.warpAffine(image, T_half, (width, height))

# Displaying the image  
cv2.imshow("Main Image", image) 
cv2.imshow("Translated Image", img_translation) 
cv2.imshow("Half Translated Image", img_half_translation) 

# Waiting 
cv2.waitKey() 
cv2.destroyAllWindows() 

In [18]:
# Viewing the matrices. 
print(T, "\n") 
print(T_half)

[[  1.   0. 150.]
 [  0.   1. 150.]] 

[[  1.   0. 300.]
 [  0.   1. 300.]]


<h3> Rotation </h3> 

<p> <b> OpenCV</b> allows you to scale and rotate at the same thing using the <b>cv2.getRotationMatrix2D</b> function. <br> 
    
<b> cv2.getRotationMatrix2D(rotation_center_x, rotation_center_y, angle_of_rotation, scale) </b> 
    
</p> 

In [19]:
# Importing the necessary modules 
import os 
import cv2 
import numpy as np 

In [27]:
# Setting the path to the image 
IMG_PATH = "images/grande2.jpg" 

# Loading the image into memory 
image = cv2.imread(IMG_PATH) 

# Getting the height and width of the image  
height, width = image.shape[:2] 

# Divide by two to rotate the image around its centre 
rotation_matrix = cv2.getRotationMatrix2D((width/2, height/2), 287, 1) 

# Getting the rotated image 
rotated_image = cv2.warpAffine(image, rotation_matrix, (width, height)) 

# Displaying the image  
cv2.imshow("Rotated Image", rotated_image) 

# Waiting for a key pressed, then destroy all windows 
cv2.waitKey() 
cv2.destroyAllWindows() 

<h3> Re-sizing, Scaling and Interpolation </h3> 

<p> What is interpolation ? <br> 

<b>Interpolation</b> is a method of constructing new data points within the range of a discrete set of known data points. <br> 
    
<b> cv2.INTER_AREA </b> - Good for shrinking or down sampling <br> 
<b> cv2.INTER_NEAREST </b> - Fastest <br> 
<b> cv2.INTER_LINEAR </b> - Good for zooming or up sampling (default) <br> 
<b> cv2.INTER_CUBIC </b> - Better <br> 
<b> cv2.INTER_LANCZOS4 </b> - Best <br> 

</p> 

<h3> Re-sizing </h3> 
<p> Re-sizing is very easy using the cv2.resize function. it's arguments are <br> 
<b>cv2.resize(image, dsize(output_image_size), x_scale, y_scale, interpolation) </b> </p> 

In [28]:
# Importing the necessary modules 
import os 
import cv2 
import numpy as np 

In [36]:
# Setting the path to the image 
IMG_PATH = "images/grande2.jpg" 

# Loading the image into memory 
image = cv2.imread(IMG_PATH) 

# Resizing the image with 3/4 of it's original size 
image_scaled = cv2.resize(image, None, fx=0.3, fy=.3) 
cv2.imshow("Scaling - Linear Interpolation", image_scaled) 
cv2.waitKey(0) 

# Resizing the image with fx=2, and fy=2, this means doubling the size of the image  
img_scaled = cv2.resize(image, None, fx=2, fy=2, interpolation = cv2.INTER_CUBIC) 
cv2.imshow("Scaling - Interpolation", img_scaled) 
cv2.waitKey(0) 

# skewing the re-sizing by setting the exact dimensions 
img_scaled = cv2.resize(image, (100, 100), interpolation = cv2.INTER_AREA) 
cv2.imshow("Scaling - Skewed Size", img_scaled) 
cv2.waitKey() 

# Destroying all windows 
cv2.destroyAllWindows() 

<h3> Cropping </h3> 

In [37]:
# Importing the necessary modules 
import os 
import cv2 
import numpy as np 

In [57]:
# Setting the path to the image 
IMG_PATH = "images/grande2.jpg" 

# Loading the image into memory 
image = cv2.imread(IMG_PATH) 

# Resizing the image with 3/4 of it's original size 
image = cv2.resize(image, None, fx=.8, fy=.8) 

# Extracting the height and width of the image 
height, width = image.shape[:2]

# Getting the starting pixels co-ordinates x1=start_column, y1=start_row 
start_row, start_col = 32, 117

# Getting the ending pixel co-ordinates x2=end_column, y2=end_row  
end_row, end_col = 204, 350

# Simply use indexing to crop out the rectangle we desire 
cropped = image[start_row:end_row, start_col:end_col] 

# Displaying both images 
cv2.imshow("Grande", image) 
cv2.imshow("Cropped Grande", cropped) 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

# print(height)

# Getting the starting pixel co-ordinate (top left of cropping rectangle) 
# start_row, start_col = 

<h3> Convolutions And Blurring </h3> 

In [2]:
# Importing the necessary modules 
import os 
import cv2 
import numpy as np 

#### First Blurring Method 

In [2]:
# Setting the path to the image 
IMG_PATH = "images/grande2.jpg" 

# Loading the image into memory 
image = cv2.imread(IMG_PATH) 

# Displaying the raw grande image 
cv2.imshow("Grande", image) 
cv2.waitKey(0) 

# Creating our 3 x 3 kernel ==> 9 
kernel_3x3 = np.ones((3, 3), np.float32) / 9 

# We use the cv2.filter2D to convolve the kernel with the image  
blurred = cv2.filter2D(image, -1, kernel_3x3) 
cv2.imshow("3x3 Kernel Blurring", blurred) 
cv2.waitKey(0) 

# Creating our 7 x 7 kernel ==> 49 
kernel_7x7 = np.ones((7, 7), np.float32) / 49 

# We use the cv2.filter2D to convolve the kernel with the image 
blurred2 = cv2.filter2D(image, -1, kernel_7x7) 
cv2.imshow("7x7 Kernel Blurring", blurred2)
cv2.waitKey(0) 

# Cleaning up 
cv2.destroyAllWindows() 

#### Second Blurring Method 

In [3]:
# Setting the path to the image 
IMG_PATH = "images/grande1.jpg"

# Loading the image into memory 
image = cv2.imread(IMG_PATH) 

# Averaging done by convolving the image with a normalized box filter. 
# This takes the pixels under the box and replaces the central element 
# Box size needs to odd and positive 
blur = cv2.blur(image, (3, 3))
cv2.imshow("Averaging", blur) 
cv2.waitKey(0) 

# Instead of box filter, gaussian kernel 
Gaussian = cv2.GaussianBlur(image, (7, 7), 0) 
cv2.imshow("Gaussian Blurring", Gaussian) 
cv2.waitKey(0) 

# Takes median of all the pixels under kernel area and central 
# Element is replaced with this media value 
median = cv2.medianBlur(image, 5) 
cv2.imshow("Median Blurring", median) 
cv2.waitKey(0) 

# Bilateral is very effective in noise removal while keeping edges sharp 
bilateral = cv2.bilateralFilter(image, 9, 75, 75) 
cv2.imshow("Bilateral Bluring", bilateral) 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

#### Image De-noising - Non-local means denoisng 

In [4]:
# Setting the path to the image 
IMG_PATH = "images/grande2.jpg" 

# Reading the image 
image = cv2.imread("images/grande1.jpg") 
image = cv2.resize(image, (300, 300), interpolation = cv2.INTER_AREA)

# Parameters, after None are - the filter strength "h" (5-10 is a good range) 
# Next is hForColorComponents, set as same value as h again. 
dst = cv2.fastNlMeansDenoisingColored(image, None, 6, 6, 7, 21) 

# Displaying the image 
cv2.imshow("Fast Means Denoising", dst) 
cv2.waitKey(0) 

# Destroying all windows 
cv2.destroyAllWindows() 

<h4> There are 4 variations of Non-Local Means Denoising: </h4> 

<ul> 
<li> cv2.fastNlMeansDenoising() - works with a single grayscale images </li> 

<li> cv2.fastNlMeansDenoisingColored() - works with a color image. </li> 

<li> cv2.fastNlMeansDenoisingMulti() - works with image sequence captured in short period of time (grayscale images) </li> 
    
<li> cv2.fastNlMeansDenoisingColoredMulti() - same as above, but for color images. </li> 
    
</ul> 